# .miserc.toml = first config read by mise
#
# This config will load first IFF placed in the correct place.
# This config is not read when in mise/config/miserc.toml
#
# To enable podman environment move to goclaw root:
# $> cp podman/config/miserc.toml .miserc.toml

env=["podman"]
